FORMAT: 1A
HOST: http://www.google.com

# agra-ranker
The agra ranker API description

# Group Greyhounds
Greyhounds related resources of the **Agra Ranker API**

## Greyhounds Collection [/greyhound]
### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Greyhound [POST]
+ Request (application/json)

        { "name": "a greyhound" }

+ Response 201 (application/json)

        { "id": 3, "name": "a greyhound" }

## Greyhound [/greyhound/{id}]
A single Greyhound object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Greyhound [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
